<div class="well well-sm">
    <form class="form-inline js_searchFrom">
        <div class="form-group">
            <label for="username">Account</label>
            <input type="text" class="form-control" id="username" placeholder="Account">
        </div>
        <div class="form-group">
            <label for="realname">Name</label>
            <input type="text" class="form-control" id="realname" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="telephone">Telephone</label>
            <input type="text" class="form-control" id="telephone" placeholder="Telephone">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
        |
        <button type="button" class="btn btn-success js_addbanner" data-toggle="modal" data-target="#addModal">Add</button>
    </form>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>

<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<!-- 新增菜单弹窗 -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">add</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="username" class="col-sm-3 control-label"><span class="required">*</span>Account</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control js_add_username" placeholder="Account">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="col-sm-3 control-label"><span class="required">*</span>Password</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control js_add_password" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="realname" class="col-sm-3 control-label"><span class="required">*</span>Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control js_add_realname" placeholder="Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="telephone" class="col-sm-3 control-label">Telephone</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control js_add_telephone" placeholder="Telephone">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">Email</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control js_add_email" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="role_id" class="col-sm-3 control-label"><span class="required">*</span>Role</label>
                        <div class="col-sm-9">
                            <select class="form-control js_add_role_id">
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="is_admin" class="col-sm-3 control-label"><span class="required">*</span>Super Admin</label>
                        <div class="col-sm-9">
                            <label class="radio-inline">
                                <input type="radio" name="is_admin" class="js_add_is_admin" value="1">Yes
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="is_admin" class="js_add_is_admin" value="0" checked="true">No
                            </label>
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> Check the info before click save button!
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_add_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- 编辑菜单弹窗 -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Edit</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" class="js_update_id">
                    <div class="form-group">
                        <label for="username" class="col-sm-3 control-label"><span class="required">*</span>Account</label>
                        <div class="col-sm-9">
                            <p class="form-control-static js_update_username"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password" class="col-sm-3 control-label"><span class="required">*</span>Password</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control js_update_password" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="realname" class="col-sm-3 control-label"><span class="required">*</span>Name</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control js_update_realname" placeholder="Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="telephone" class="col-sm-3 control-label">Telephone</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control js_update_telephone" placeholder="Telephone">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email" class="col-sm-3 control-label">Email</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control js_update_email" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="role_id" class="col-sm-3 control-label"><span class="required">*</span>Role</label>
                        <div class="col-sm-9">
                            <select class="form-control js_update_role_id">
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="is_admin" class="col-sm-3 control-label"><span class="required">*</span>Super Admin</label>
                        <div class="col-sm-9">
                            <label class="radio-inline">
                                <input type="radio" name="is_admin" class="js_update_is_admin" value="1">Yes
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="is_admin" class="js_update_is_admin" value="0">No
                            </label>
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> Check the info before click save button!
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- 确认删除弹窗 -->
<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Tips
            </div>
            <div class="modal-body">
                Do you confirm to change?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary js_sure_delete">Confirm</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="<?php echo $resource_url; ?>js/system/admin_index.js?v=1"></script>
