<style media="screen">
.table-responsive{
  width: 100%;
}
.table{
  width: 100%;
}
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>/css/uploadifive.css">
<button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">Add</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>
<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Edit</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="id" class="col-sm-4 control-label">no.</label>
                        <div class="col-sm-8">
                            <p class="form-control-static js_id"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">link</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_link" placeholder="链接">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="photo" class="col-sm-4 control-label">img
                            <button type="button" class="btn btn-primary js_upload" data-toggle="modal" data-target="#uploadModal"><span class="glyphicon glyphicon-plus"></span></button></label>
                        <div class="col-sm-8">
                            <img class="img-responsive js_photo_prev img-thumbnail" style="width:120px; height: 60px;">
                            <input type="hidden" class="form-control js_photo" placeholder="将要修改的图片url粘贴到这里，留空表示不需要修改图片">
                        </div>
                    </div>
                    <div class="form-group" style='line-height: 5px'>
                        <label for="url" class="col-sm-4 control-label">status</label>
                        <div class="col-sm-8">
                            <select class="js_select" name="">
                              <option value="0">show</option>
                              <option value="1">hide</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="aorder" class="col-sm-4 control-label">sort(the bigger the number is ranked previous)</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_sort" placeholder="sort(the bigger the number is ranked previous)">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> Check the info before click save button!
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">新增</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">link</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_link" placeholder="link">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="photo" class="col-sm-4 control-label">img
                            <button type="button" class="btn btn-primary js_add_upload" data-toggle="modal" data-target="#uploadModal"><span class="glyphicon glyphicon-plus"></span></button></label>
                        <div class="col-sm-8">
                            <img class="img-responsive js_add_photo_prev img-thumbnail" style="width:120px; height: 60px;">
                            <input type="hidden" class="form-control js_add_photo" placeholder="将要修改的图片url粘贴到这里，留空表示不需要修改图片">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">status</label>
                        <div class="col-sm-8">
                            <select class="js_add_select" name="">
                              <option value="0">show</option>
                              <option value="1">hide</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="aorder" class="col-sm-4 control-label">sort(the bigger the number is ranked previous)</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_sort" value="100">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> Check the info before click save button!
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_add_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="uploadModal" tabindex="1" role="dialog" aria-labelledby="uploadModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Image Upload</h4>
            </div>
            <div class="modal-body">
                <input id="photo" type="file" multiple="false" value="" />
                <div>
                    <img src="" id="prevArea" style="max-width: 100px; max-height: 100px; ">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary js_addPhoto">Confirm</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Tips
            </div>
            <div class="modal-body">
                Do you confirm to change?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary js_sure_delete">Confirm</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="" charset="utf-8"></script>
<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>js/banner.js"></script>
