<style media="screen">
.table-responsive{
  width: 100%;
}
.table{
  width: 100%;
}
.property_add{
  /* display: none */
}
.ticket_add{
  display: none
}
.property_update{
  display: none
}
.ticket_update{
  display: none
}

</style>
<link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>/css/uploadifive.css">
<button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">Add</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>
<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Edit</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="id" class="col-sm-4 control-label">Serial No.</label>
                        <div class="col-sm-8">
                            <p class="form-control-static js_id"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label style="padding-top:0" for="url" class="col-sm-4 control-label">Link</label>
                        <div class="col-sm-8">
                          <!-- <input type="text" class="form-control js_update_link" placeholder="链接"> -->
                          <label><input type="radio" name="update_link" value="1">Property</label>
                          <label><input type="radio" name="update_link" value="2">Ticket</label>
                        </div>
                        <label style="padding-top:0" for="url" class="col-sm-4 control-label"></label>
                        <div class="col-sm-8">
                          <button type="button" class="btn btn-primary js_select_update_ticket ticket_update" data-toggle="modal" data-target="#selectUpdateTicketModal"><span class="">Select Update Ticket</span></button>
                        </div>
                    </div>
                    <div class="form-group property_update">
                        <label style="padding-top:0" class="col-sm-4 control-label">Property Name</label>
                        <div class="col-sm-8">
                          <select class="propertyName" name="" id="update_property_id">
                            <option value="">Select</option>
                            <?php foreach ($propertyList as $k => $v): ?>
                              <option value="<?=$v["propertyID"]?>"><?=$v["propertyName"]?></option>
                            <?php endforeach; ?>
                          </select>
                        </div>
                    </div>
                    <div class="form-group ticket_update">
                        <label class="col-sm-4 control-label">Ticket ID</label>
                        <div class="col-sm-8">
                            <input disabled type="text" class="form-control" id="update_ticket_id">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="photo" class="col-sm-4 control-label">Image
                            <button type="button" class="btn btn-primary js_upload" data-toggle="modal" data-target="#uploadModal"><span class="glyphicon glyphicon-plus"></span></button></label>
                        <div class="col-sm-8">
                            <img class="img-responsive js_photo_prev img-thumbnail" style="width:120px; height: 60px;">
                            <input type="hidden" class="form-control js_photo" placeholder="将要修改的图片url粘贴到这里，留空表示不需要修改图片">
                        </div>
                    </div>
                    <div class="form-group" style='line-height: 5px'>
                        <label for="url" class="col-sm-4 control-label">Status</label>
                        <div class="col-sm-8">
                            <select class="js_select" name="">
                              <option value="0">Show</option>
                              <option value="1">Hide</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="aorder" class="col-sm-4 control-label">Rank(Sort Desending)</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_sort" placeholder="Rank(Sort Desending)">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> Check the info before click save button!
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Add</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label style="padding-top:0" for="url" class="col-sm-4 control-label">Link</label>
                        <div class="col-sm-8">

                          <label><input type="radio" name="link" value="1" checked>Property</label>
                          <label><input type="radio" name="link" value="2">Ticket</label>
                        </div>
                        <label style="padding-top:0" for="url" class="col-sm-4 control-label"></label>
                        <div class="col-sm-8">
                          <button type="button" class="btn btn-primary js_select_ticket ticket_add" data-toggle="modal" data-target="#selectTicketModal"><span class="">Select Ticket</span></button>
                        </div>
                    </div>
                    <div class="form-group property_add">
                        <label style="padding-top:0" class="col-sm-4 control-label">Property Name</label>
                        <div class="col-sm-8">
                          <select class="propertyName" name="" id="property_id">
                            <option value="">Select</option>
                            <?php foreach ($propertyList as $k => $v): ?>
                              <option value="<?=$v["propertyID"]?>"><?=$v["propertyName"]?></option>
                            <?php endforeach; ?>
                          </select>
                        </div>
                    </div>
                    <div class="form-group ticket_add">
                        <label class="col-sm-4 control-label">Ticket ID</label>
                        <div class="col-sm-8">
                            <input disabled type="text" class="form-control" id="ticket_id">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="photo" class="col-sm-4 control-label">Image
                            <button type="button" class="btn btn-primary js_add_upload" data-toggle="modal" data-target="#uploadModal"><span class="glyphicon glyphicon-plus"></span></button></label>
                        <div class="col-sm-8">
                            <img class="img-responsive js_add_photo_prev img-thumbnail" style="width:120px; height: 60px;">
                            <input type="hidden" class="form-control js_add_photo" placeholder="将要修改的图片url粘贴到这里，留空表示不需要修改图片">
                        </div>
                    </div>
                    <div class="form-group">
                        <label style="padding-top:0" for="url" class="col-sm-4 control-label">Status</label>
                        <div class="col-sm-8">
                            <select class="js_add_select" name="">
                              <option value="0">Show</option>
                              <option value="1">Hide</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="aorder" class="col-sm-4 control-label">Rank(Sort Desending)</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_sort" value="100">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> Check the info before click save button!
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_add_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="selectTicketModal" tabindex="1" role="dialog" aria-labelledby="selectTicketModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Select Ticket</h4>
            </div>
            <div class="modal-body">
              <div class="well well-sm">
                  <form class="form-inline js_searchFrom">
                      <div class="form-group">
                          <label for="search_name">Ticket Title</label>
                          <input type="text" class="form-control" id="search_title" placeholder="Ticket Title">

                      </div>

                      <button type="submit" class="btn btn-sm btn-primary">Search</button>
                  </form>
              </div>
              <div class="table-responsive">
                    <table class="table js_table2">
                    </table>
              </div>
              <div class="table_page">
                <nav style="float:right;">
                    <ul class="pagination js_page2"></ul>
                </nav>
              </div>

            </div>
            <div class="modal-footer">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="selectUpdateTicketModal" tabindex="1" role="dialog" aria-labelledby="selectUpdateTicketModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Select Update Ticket</h4>
            </div>
            <div class="modal-body">
              <div class="well well-sm">
                  <form class="form-inline js_searchFrom2">
                      <div class="form-group">
                          <label for="search_name">Ticket Title</label>
                          <input type="text" class="form-control" id="search_title2" placeholder="Ticket Title">

                      </div>

                      <button type="submit" class="btn btn-sm btn-primary">Search</button>
                  </form>
              </div>
              <div class="table-responsive">
                    <table class="table js_table3">
                    </table>
              </div>
              <div class="table_page">
                <nav style="float:right;">
                    <ul class="pagination js_page3"></ul>
                </nav>
              </div>

            </div>
            <div class="modal-footer">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="uploadModal" tabindex="1" role="dialog" aria-labelledby="uploadModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Image Upload</h4>
            </div>
            <div class="modal-body">
                <input id="photo" type="file" multiple="false" value="" />
                <div>
                    <img src="" id="prevArea" style="max-width: 100px; max-height: 100px; ">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary js_addPhoto">Confirm</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Tips
            </div>
            <div class="modal-body">
                Do you confirm to change?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary js_sure_delete">Confirm</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="" charset="utf-8"></script>
<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>js/banner.js"></script>
