<link rel="stylesheet" href="<?php echo $resource_url; ?>libs/summernote/summernote.css">

<style type="text/css">
    .prev-pic {
        max-width: 400px;
        max-height: 300px;
        display: block;
        margin: 20px;
        border: 1px solid #ccc;
        padding: 10px;
    }
    .prev-frame {
        display: inline-block;
        position: relative;
    }
    .prev-frame em {
        position: absolute;
        right: 25px;
        top: 20px;
        background: red;
        display: inline-block;
        width: 20px;
        height: 20px;
        text-align: center;
        color: #fff;
        font-weight: 1000;
        cursor: pointer;
    }
</style>

<div class="form-group">
    <label>Property ID</label>
    <input type="text" class="form-control" id="propertyID" disabled value="<?php echo $info['propertyID']; ?>">
</div>
<div class="form-group">
    <label>Property Name</label>
    <input type="text" class="form-control" id="propertyName" placeholder="Property Name" value="<?php echo $info['propertyName']; ?>">
</div>
<div class="form-group">
    <label>Property Name(chinese)</label>
    <?php if(isset($info2)): ?>
      <input type="text" class="form-control" id="propertyNameCh" placeholder="propertyNameCh" value="<?php echo $info2['propertyName']; ?>">
    <?php else: ?>
      <input type="text" class="form-control" id="propertyNameCh" placeholder="propertyNameCh" value="">
    <?php endif; ?>
</div>
<div class="form-group">
    <label>Property Phone</label>
    <input type="text" class="form-control" id="propertyPhone" placeholder="propertyPhone" value="<?php echo $info['propertyPhone']; ?>">
</div>
<div class="form-group">
    <label>Property Email</label>
    <input type="text" class="form-control" id="propertyEmail" placeholder="propertyEmail" value="<?php echo $info['propertyEmail']; ?>">
</div>

<div class="form-group">
    <label>Property Address1</label>
    <input type="text" class="form-control" id="propertyAddress1" placeholder="propertyAddress1" value="<?php echo $info['propertyAddress1']; ?>">
</div>
<div class="form-group">
    <label>Property Address2</label>
    <input type="text" class="form-control" id="propertyAddress2" placeholder="propertyAddress2" value="<?php echo $info['propertyAddress2']; ?>">
</div>
<div class="form-group">
    <label>Address(chinese)</label>
    <?php if(isset($info2)): ?>
      <input type="text" class="form-control" id="propertyAddressCh" placeholder="propertyAddressCh" value="<?php echo $info2['propertyAddress']; ?>">
    <?php else: ?>
      <input type="text" class="form-control" id="propertyAddressCh" placeholder="propertyAddressCh" value="">
    <?php endif; ?>
</div>
<div class="form-group">
    <label>Property City</label>
    <input type="text" class="form-control" id="propertyCity" value="<?php echo $info['propertyCity']; ?>">
</div>
<div class="form-group">
    <label>Property State</label>
    <input type="text" class="form-control" id="propertyState" value="<?php echo $info['propertyState']; ?>">
</div>
<div class="form-group">
    <label>Property Zip</label>
    <input type="text" class="form-control" id="propertyZip" value="<?php echo $info['propertyZip']; ?>">
</div>
<div class="form-group">
    <label>Property Country</label>
    <input type="text" class="form-control" id="propertyCountry" value="<?php echo $info['propertyCountry']; ?>">
</div>
<div class="form-group">
    <label>Property Latitude</label>
    <input type="text" class="form-control" id="propertyLatitude" value="<?php echo $info['propertyLatitude']; ?>">
</div>
<div class="form-group">
    <label>Property Longitude</label>
    <input type="text" class="form-control" id="propertyLongitude" value="<?php echo $info['propertyLongitude']; ?>">
</div>
<div class="form-group">
    <label>Check In Time</label>
    <input type="text" class="form-control" id="propertyCheckInTime" value="<?php echo $info['propertyCheckInTime']; ?>">
</div>
<div class="form-group">
    <label>Check Out Time</label>
    <input type="text" class="form-control" id="propertyCheckOutTime" value="<?php echo $info['propertyCheckOutTime']; ?>">
</div>
<!-- <div class="form-group">
    <label>Late Check Out Allowed</label>
    <input type="text" class="form-control" id="propertyLateCheckOutAllowed" value="<?php echo $info['propertyLateCheckOutAllowed']; ?>">
</div>
<div class="form-group">
    <label>Late Check Out Type</label>
    <input type="text" class="form-control" id="propertyLateCheckOutType" value="<?php echo $info['propertyLateCheckOutType']; ?>">
</div>
<div class="form-group">
    <label>Late Check Out Value</label>
    <input type="text" class="form-control" id="propertyLateCheckOutValue" value="<?php echo $info['propertyLateCheckOutValue']; ?>">
</div> -->
<div class="form-group">
    <label>Terms And Conditions</label>
    <div id="termsAndConditions"></div>
</div>
<div class="form-group">
    <label>Property Amenities</label>
    <input type="text" class="form-control" id="propertyAmenities" value="<?php echo $info['propertyAmenities']; ?>">
</div>
<div class="form-group">
    <label>Property Description</label>
    <div id="descript"></div>
</div>
<div class="form-group">
    <label>Property Description(chinese)</label>
    <div id="descriptCh"></div>
</div>
<!-- <div class="form-group">
    <label>Property Timezone</label>
    <input type="text" class="form-control" id="propertyTimezone" value="<?php echo $info['propertyTimezone']; ?>">
</div>
<div class="form-group">
    <label>Currency Code</label>
    <input type="text" class="form-control" id="propertyCurrencyCode" value="<?php echo $info['propertyCurrencyCode']; ?>">
</div>
<div class="form-group">
    <label>Currency Symbol</label>
    <input type="text" class="form-control" id="propertyCurrencySymbol" value="<?php echo $info['propertyCurrencySymbol']; ?>">
</div>
<div class="form-group">
    <label>Currency Position</label>
    <input type="text" class="form-control" id="propertyCurrencyPosition" value="<?php echo $info['propertyCurrencyPosition']; ?>">
</div> -->
<div class="form-group">
    <label>Recommend</label>
    <!-- <input type="text" class="form-control" id="propertyStatus" value="<?php echo $info['status']; ?>"> -->
    <select class="selectRecommend">
      <option value="0">Not Recommend</option>
      <option value="1">Recommend</option>
      <option value="2">Waterfall</option>
    </select>
</div>
<div class="form-group">
    <label>Property Status</label>
    <!-- <input type="text" class="form-control" id="propertyStatus" value="<?php echo $info['status']; ?>"> -->
    <select class="selectStatus">
      <option value="0">Unchecked</option>
      <option value="1">Approve</option>
      <option value="2">Deny</option>
    </select>
</div>


<textarea class="js_descript" style="display: none;"><?php echo $info['propertyDescription']; ?></textarea>
<textarea class="js_terms_and_conditions" style="display: none;"><?php echo $info['propertyTermsAndConditions']; ?></textarea>
<?php if(isset($info2)): ?>
  <textarea class="js_descript_ch" style="display: none;"><?php echo $info2['propertyDescription']; ?></textarea>
<?php else: ?>
  <textarea class="js_descript_ch" style="display: none;"></textarea>
<?php endif; ?>

<input type="hidden" name="id" value="<?php echo $id; ?>" class="js_id">

<button type="submit" class="btn btn-primary js_submit">Save</button>

<script src="<?php echo $resource_url; ?>libs/summernote/summernote.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-CN.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-TW.js"></script>
<script src="<?php echo $resource_url; ?>js/hotel_update.js"></script>
<script type="text/javascript">
$(function() {
    $('#termsAndConditions').summernote('code', $('.js_terms_and_conditions').val());
    $('#descript').summernote('code', $('.js_descript').val());
    $('#descriptCh').summernote('code', $('.js_descript_ch').val());
    var status = <?php echo $info['status']?>;
    var recommend = <?php echo $info['recommend']?>;
    $('.selectStatus').val(status);
    $('.selectRecommend').val(recommend);
})
</script>
