<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Personal Information</h3>
    </div>
    <div class="panel-body">
        <form class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label">Account:</label>
                <div class="col-sm-10">
                    <p class="form-control-static" style="display: inline-block; margin-right: 30px;"><?php echo $adminDetail['username']; ?></p>
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#editModal">Change Password</button>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Name:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $adminDetail['realname']; ?></p>
                </div>
            </div>
            <?php if($adminDetail['is_admin']!='1') { ?>
            <div class="form-group">
                <label class="col-sm-2 control-label">Role:</label>
                <div class="col-sm-10">
                    <p class="form-control-static">
                        <?php
                        if(count($adminDetail['roleInfo']) > 0) {
                            echo $adminDetail['roleInfo']['name'] . '（' . $adminDetail['roleInfo']['pmsName'] . '）';
                        } else {
                            echo '暂未分配角色！';
                        }
                        ?>
                    </p>
                </div>
            </div>
            <?php } ?>
            <div class="form-group">
                <label class="col-sm-2 control-label">Telephone:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $adminDetail['telephone']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Email:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $adminDetail['email']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Super Admin:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php if($adminDetail['is_admin']=='1') { echo '<span style="color: green;">是</span>'; } else { echo '<span style="color: red;">否</span>'; } ?></p>
                </div>
            </div>
        </form>
    </div>
</div>

<?php if($adminDetail['is_admin']=='1') { ?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">System Information</h3>
    </div>
    <div class="panel-body">
        <form class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-2 control-label">Operation System:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $systemInfo['uname']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Server Info:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $systemInfo['server_software']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Server Address:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $systemInfo['server_name']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Server Port:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $systemInfo['http_port']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">PHP Version:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $systemInfo['php_version']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">PHP Mode:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $systemInfo['php_sapi_name']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">MYSQL Version:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $systemInfo['mysql_version']; ?></p>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">System Time:</label>
                <div class="col-sm-10">
                    <p class="form-control-static"><?php echo $systemInfo['system_time']; ?></p>
                </div>
            </div>
        </form>
    </div>
</div>
<?php } ?>

<div class="modal fade" id="editModal" tabindex="1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Change Password</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="username" class="col-sm-3 control-label">Account</label>
                        <div class="col-sm-9">
                            <p class="form-control-static"><?php echo $adminDetail['username']; ?></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password_ole" class="col-sm-3 control-label"><span class="required">*</span>Old Password</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control js_password_old" placeholder="old password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password_new" class="col-sm-3 control-label"><span class="required">*</span>New Password</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control js_password_new" placeholder="New Password">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="password_new1" class="col-sm-3 control-label"><span class="required">*</span>Confirm New Password</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control js_password_new1" placeholder="Confirm New Password">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong>Check the info before click save button!
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $resource_url; ?>js/index.js"></script>
