<style media="screen">
.table-responsive{
  width: 100%;
}
.table{
  width: 100%;
}
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>/css/uploadifive.css">
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>
<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Edit</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="id" class="col-sm-4 control-label">Serial No.</label>
                        <div class="col-sm-8">
                            <p class="form-control-static js_id"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="totalAmount" class="col-sm-4 control-label">Property City</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_propertyCity" placeholder="Property City">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="discountAmount" class="col-sm-4 control-label">Property City(Chinese)</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_propertyCity_cn" placeholder="Property City(Chinese)">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="status" class="col-sm-4 control-label" style="line-height:5px">Status</label>
                        <div class="col-sm-8">
                            <select class="js_select" name="">
                              <option value="0">Hide</option>
                              <option value="1">Show</option>
                              <option value="2">Off</option>
                            </select>
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong>Check the info before click save button!
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save Changes</button>
            </div>
        </div>
    </div>
</div>


<script src="" charset="utf-8"></script>
<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>js/location.js"></script>
