<button type="button" class="btn btn-sm btn-primary js_add" style="margin-bottom:10px;">Add</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>

<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<!-- 确认删除弹窗 -->
<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Tips
            </div>
            <div class="modal-body">
                Do you confirm to change?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary js_sure_delete">Confirm</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="<?php echo $resource_url; ?>js/system/role_index.js"></script>
