<style media="screen">
  .table-responsive{
    width: 100%;
  }
</style>
<div class="well well-sm">
    <form class="form-inline js_searchFrom">
        <div class="form-group">
            <label for="search_name">Property Name</label>
            <!-- <input type="text" class="form-control" id="search_name" placeholder="Property Name"> -->
            <select class="propertyName" name="" id="properyName">
              <option value="">All</option>
              <?php foreach ($propertyList as $k => $v): ?>
                <option value="<?=$v["propertyID"]?>"><?=$v["propertyName"]?></option>
              <?php endforeach; ?>

            </select>

        </div>

        <button type="submit" class="btn btn-sm btn-primary">Search</button>
    </form>
</div>
<!-- <button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">新增</button> -->
<div class="table-responsive">
    <!-- <div class="table_l"> -->
      <table class="table js_table">
      </table>
    <!-- </div> -->
    <!-- <div class="table_r">
      <table class="table js_table2">
      </table>
    </div> -->
</div>
<div class="table_page">
  <nav style="float:right;">
      <ul class="pagination js_page"></ul>
  </nav>
</div>






<script src="<?php echo $resource_url; ?>js/rooms_index.js"></script>
