<style media="screen">
  .table-responsive{
    width: 100%;
  }
</style>
<div class="well well-sm">
    <form class="form-inline js_searchFrom">
        <div class="form-group">
            <label for="search_name">Ticket Title</label>
            <input type="text" class="form-control" id="search_title" placeholder="Ticket Title">

        </div>

        <button type="submit" class="btn btn-sm btn-primary">Search</button>
    </form>
</div>
<!-- <button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">新增</button> -->
<div class="table-responsive">
    <!-- <div class="table_l"> -->
      <table class="table js_table">
      </table>
    <!-- </div> -->
    <!-- <div class="table_r">
      <table class="table js_table2">
      </table>
    </div> -->
</div>
<div class="table_page">
  <nav style="float:right;">
      <ul class="pagination js_page"></ul>
  </nav>
</div>






<script src="<?php echo $resource_url; ?>js/ticket_index.js"></script>
