<style media="screen">
.table-responsive{
  width: 100%;
}
.table{
  width: 100%;
}
</style>
<link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>/css/uploadifive.css">
<!-- <button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">新增</button> -->
<div class="well well-sm">
    <form class="form-inline">
        <button type="" id="export" class="btn btn-primary">Export</button>
    </form>
</div>

<div class="well well-sm">
    <form class="form-inline js_searchFrom">
        <div class="form-group">
            <label for="search_name">Wechat Nickname</label>
            <input type="text" class="form-control" id="search_name" placeholder="Nickname">
        </div>
        <button type="submit" class="btn btn-sm btn-primary">Search</button>
    </form>
</div>

<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>
<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<div class="modal fade" id="propertyModal" tabindex="-1" role="dialog" aria-labelledby="propertyModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Property Order Record</h4>
            </div>
            <div class="modal-body">
              <div class="table-responsive">
                  <table class="table table-striped table-hover js_table2">

                  </table>
              </div>

            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="ticketModal" tabindex="-1" role="dialog" aria-labelledby="ticketModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Ticket Order Record</h4>
            </div>
            <div class="modal-body">
              <div class="table-responsive">
                  <table class="table table-striped table-hover js_table3">

                  </table>
              </div>

            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="couponModal" tabindex="-1" role="dialog" aria-labelledby="couponModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Coupon Order Record</h4>
            </div>
            <div class="modal-body">
              <div class="table-responsive">
                  <table class="table table-striped table-hover js_table4">

                  </table>
              </div>

            </div>

        </div>
    </div>
</div>

<script src="" charset="utf-8"></script>
<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>js/user.js"></script>
