<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="linzequan" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <title>佛山市顺德区教育基金会</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 引入样式 -->
    <link rel="stylesheet" href="<?php echo $resource_url; ?>libs/ydui/ydui.rem.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>libs/weui/weui.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/common.css">
    <!-- 引入rem自适应类库 -->
    <script src="<?php echo $resource_url; ?>libs/ydui/ydui.flexible.js"></script>
    <!-- 引入 Vue -->
    <script src="<?php echo $resource_url; ?>libs/vue.js"></script>
    <!-- 引入组件库 -->
    <script src="<?php echo $resource_url; ?>libs/ydui/ydui.rem.js"></script>
    <script src="<?php echo $resource_url; ?>libs/weui/weui.min.js"></script>
    <script type="text/javascript" src="<?php echo $resource_url; ?>js/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $resource_url; ?>js/common.js"></script>
</head>
<body>
